name: Shashwat Raghuvanshi
url: https://shashwatraghuvanshi.com
description: "Welcome to my Personal Page."

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
